### ISSUE TITLE
Report.md

### ISSUE THREAD

**Issue by laszewsk** [cybertraining-dsc/fa20-523-350#1]
This document will not be reviewed as it is not in the proper format and does not meat our filename requirements

**Comment by laszewsk** [comment]
your document is not proper markdown and breaks our web site. I go ahead and try to make it proper markdown, but it will be excluded from review

**Comment by laszewsk** [comment]
file renamed to broken-report.md

**Comment by laszewsk** [comment]
you must decide if you do a project or a report. dependent on this your file and directory name needs to be chosen as posted in the guidelines

**Comment by laszewsk** [comment]
why not continue in project.md ?

**Comment by ghost** [comment]
I've decided to do a report instead of a project for the same topic, because I don't have the computing power to train the large neural networks I'm writing about.
